name: CI
on:
  push:
    branches:
      - "*"
      - "**"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          run_install: true
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Test
        run: pnpm ci:test
  check:
    if: ${{github.ref_name=='main'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: jsr-dry-run
        run: npx jsr publish --dry-run
