name: Publish
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{fromJson(env.PACKAGE_JSON).version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Build
        run: pnpm run ci:build
      - name: Check Api
        run: pnpm run ci:check-api
      
      - name: jsr-dry-run
        run: npx jsr publish --dry-run
      - name: npm-dry-run
        run: npm publish --dry-run

      - name: Read packageJson
        run: |
          {
            echo 'PACKAGE_JSON<<EOF' 
            cat ./package.json
            echo EOF
          } >>  $GITHUB_ENV
      - name: Package npm
        run: |
          npm pack
          mv asla-yoursql-${{fromJson(env.PACKAGE_JSON).version}}.tgz npm-package.tgz
      - name: Upload npm package
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: |
            npm-package.tgz
          retention-days: 3

  publish-npm:
    needs: check
    if: ${{github.repository_owner=='asnowc'}}
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: npm-package
      - name: Unpack
        run: tar -zxvf npm-package.tgz
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - name: Publish
        run: npm publish
        working-directory: ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-jsr:
    runs-on: ubuntu-latest
    needs: check
    if: ${{github.repository_owner=='asnowc'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        run: npx jsr publish
